### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by barcus** [stephanediondev/elasticsearch-admin#51]
Hello,

Thank you for this great tool :)

I get internal error with somes pages like when i try to sort index by creation date.
I can display first page of index list but for exemple page 3 does not work.
It looks like i have some trouble with at least one index>

App\Twig\AppExtension::humanFilesize(): Argument #1 ($size) must be of type int, null given, called in /var/www/html/var/cache/prod/twig/e7/e7299cadd84416a1bc00cf714c7b3304fc93b41076cb96819eb436e3e1ccc3a6.php on line 384

    File: /var/www/html/src/Twig/AppExtension.php
    Line: 43
    Route: indices

    Installation type: docker
    PHP version: 8.0.17
    Symfony version: 6.0.7
    Elasticsearch version: 7.12.1

    Browser: Firefox 99.0
    OS: Mac 10.15

Any idea how can i identify it ?

**Comment by stephanediondev** [comment]
Hello

Even with zero documents the index should have a minimum size.

You can use the menu Tools and first item CAT
- Command = indices
- Sort = store.size:asc

Probably one or more indices have an empty/undefined size


For safety I can add a condition on the nice indices list if there is an empty size

**Comment by barcus** [comment]
There a 2 indices with "close" status. There is no information about store.size or docs.count !

**Comment by stephanediondev** [comment]
I see

I made an update, now the size can be null

**Comment by barcus** [comment]
It works 👍
