### ISSUE TITLE
Nodes view not available when node cpu not supported

### ISSUE THREAD

**Issue by barcus** [stephanediondev/elasticsearch-admin#61]
Hello,

I got at internal error when i try to display nodes.
I seems to be linked to my new nodes, which reports `-1` as a CPU percent value in nodes API

Error logs:
`NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php on line 92`

`NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 1`

`2022/11/22 12:39:38 [error] 9#9: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/symfony/http-client/Response/CommonResponseTrait.php on line 92PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 1" while reading response header from upstream, client: 10.2.131.143, server: _, request: "GET /admin/nodes HTTP/1.1"`

_cat/nodes API result:
`10.152.240.42 58 98 -1 0.22 0.18 0.32 cdfhlrstw - esc1-cold-6q32` 

nodes API result for nodes/stats/os:
`      "os": {
        "timestamp": 1669121185576,
        "cpu": {
          "percent": -1,
          "load_average": {
            "1m": 0.35,
            "5m": 0.22,
            "15m": 0.3
          }
        },
        "mem": {
          "total_in_bytes": 16786419712,
          "free_in_bytes": 264089600,
          "used_in_bytes": 16522330112,
          "free_percent": 2,
          "used_percent": 98
        },`

Thanks a lot !

**Comment by barcus** [comment]
Looks like i need to upgrade to Elastic 7.16 to be compliant with my new Debian 11 nodes !
Could be nice to be able to display nodes until i upgrade :)

**Comment by stephanediondev** [comment]
Hi

Not sure it's related to data. I made a test to overwrite the values ['stats']['process']['cpu']['percent'] and ['stats']['os']['cpu']['percent'], no issue

I think for this node you have more data than usual when you get responses from Elasticsearch and PHP need more memory to handle all

CommonResponseTrait.php on line 92 => json_decode used for the response from Elasticsearch

Can you upgrade the value "memory_limit" in your php.ini? 200M at least

**Comment by barcus** [comment]
ok my bad 🤦‍♂️ 
thank you !
