### ISSUE TITLE
Helm chart for elasticsearch-admin

### ISSUE THREAD

**Issue by mooncser** [stephanediondev/elasticsearch-admin#64]
Is there any existing helm chart for the elasticsearch-admin project? Thank you!

**Comment by stephanediondev** [comment]
No

**Comment by mooncser** [comment]
@stephanediondev Thanks very much. I am not familiar with PHP. Is there any ENV variable to set the application context path? Otherwise, I need to change the nginx configuration. There are some issues when I deployed the application to the k8s cluster.

**Comment by stephanediondev** [comment]
Hi

What do you call "the application context path" ?
Do you need to change the "public" folder ?
It's not possible with ENV variable

https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory
