### ISSUE TITLE
Node filter in Shards page not filled

### ISSUE THREAD

**Issue by pandvan** [stephanediondev/elasticsearch-admin#68]
Hi, first of all thank you for this product, it looks very promising.

I'm facing as issue with _Shard_ page. The "Node" filter listbox is not filled with the cluster nodes, so I can't filter by this criteria.
Further, if I click one of the links from `Shards -> Stats -> Shards by node`, it doesn't work and shows the error: `The selected choice is invalid.`

![image](https://github.com/stephanediondev/elasticsearch-admin/assets/22728755/64abb216-f1da-46ca-bb09-b9e668cc1bc3)

Can't see any significant error from logs. At the moment I'm running `elasticsearch-admin` on a local container.

**Comment by pandvan** [comment]
Neither node has `data` in its main roles.
We don't use `data` role, instead we use `data_hot`, `data_warm`, `data_host` for tiering.

![image](https://github.com/stephanediondev/elasticsearch-admin/assets/22728755/4591a580-b764-4e03-992e-9e4ae3c5bee7)

Here an excerpt of `_cat/nodes` API

```
node.role name
hilmrst   node-1
hilmrst   node-2
w         node-4
w         node-5
c         node-6
c         node-7
mv        tiebreaker
```

Elasticsearch is running on version 8.7.1

**Comment by stephanediondev** [comment]
Ok

I have removed the limitation to "data" role, now you have all the nodes.

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-node
"A node can belong to multiple tiers, but a node that has one of the specialized data roles cannot have the generic data role."


New release 1.78

Commit https://github.com/stephanediondev/elasticsearch-admin/commit/9edbe3ae3af16286b81da1c3475a4b5aecc8cb9e

**Comment by pandvan** [comment]
Perfect, I'll going to try in a while.
Could it be possible to add `data_*` badges (or something similar) on "main roles" in the nodes list?

**Comment by stephanediondev** [comment]
Yes it's possible

I will improve to have the generic and specialised data roles in badges + included in filter "data" yes/no

**Comment by pandvan** [comment]
Just tried the new version and I can confirm the issue has been solved.
Thanks.
