### ISSUE TITLE
cluster.indices.close.enable 

### ISSUE THREAD

**Issue by Poil** [stephanediondev/elasticsearch-admin#75]
Hi,

The audit report :
Closing an index is not allowed: Fail
The setting cluster.indices.close.enable should be set to false. 

But I think it should be set to true ? (that is the default value) to allow closing indexes ?

Regards

**Comment by stephanediondev** [comment]
Hi

There is a note in ES documentation: "Closed indices consume a significant amount of disk-space which can cause problems in managed environments."

But I have removed this audit checkpoint anyway: it depends if you need closed indices or not
