### ISSUE TITLE
Error when going to Cluster -> Audit

### ISSUE THREAD

**Issue by mackfish-1** [stephanediondev/elasticsearch-admin#78]
Really like this ES admin tool - THANK YOU

playing around with it, I get this when going to  Cluster -> Audit

Internal Server Error
App\Model\ElasticsearchSlmPolicyModel::setIndices(): Argument #1 ($indices) must be of type ?array, string given, called in /var/www/html/src/Model/ElasticsearchSlmPolicyModel.php on line 349

File: /var/www/html/src/Model/ElasticsearchSlmPolicyModel.php
Line: 111
Route: cluster_audit
Installation type: docker
PHP version: 8.2.17
Symfony version: 7.0.5
Elasticsearch version: 7.8.0
Browser: Chrome 126.0
OS: Windows 10

**Comment by stephanediondev** [comment]
Hi

It's fixed

Issue with SLM policies: indices parameter can be array or string
