### ISSUE TITLE
Roles - cannot add permissions

### ISSUE THREAD

**Issue by mackfish-1** [stephanediondev/elasticsearch-admin#79]
Tried to add permissions to "Application->Roles->[role]->update"

When adding a permission to the role it flashes up "Added: PERMISSION" but it is not saved.

I cannot see it in the ".elasticsearch-admin-roles" index either.

the record just says

{
  "name": "ROLE_INDEXRW",
  "created_at": "2024-06-19 08:22:40"
}

**Comment by mackfish-1** [comment]
I note that the index ".elasticsearch-admin-permissions" wasn't created. and even when created, it wasn't written into.

by manually adding the index and the record, I was able to add the permission

**Comment by stephanediondev** [comment]
Hi

It's fixed

Requests POST are now allowed (instead of GET) to save permissions
